services:
  patch:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    command: patch
    volumes:
      - ./public:/app/dist/public
    ports:
      - "80:80"
      - "8080:8080"

  master:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: master
    ports:
      - "81:81"

  game1:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 1 -p 8085
    ports:
      - "8085:8085/udp"

  game2:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
    - MASTER_INTERNAL_IP=master
    command: game 2 -p 8086
    ports:
      - "8086:8086/udp"

  game3:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 3 -p 8087
    ports:
      - "8087:8087/udp"

  teamgame1:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 1 2 -p 8088
    ports:
      - "8088:8088/udp"

  teamgame2:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 2 2 -p 8089
    ports:
      - "8089:8089/udp"

  teamgame3:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 3 2 -p 8090
    ports:
      - "8090:8090/udp"

  teamgame4:
    image: minextu/ssc-server
    build: .
    restart: on-failure
    env_file: ".env"
    environment:
      - MASTER_INTERNAL_IP=master
    command: game 4 2 -p 8091
    ports:
      - "8091:8091/udp"